n = (input('Digite algo para análise: '))
print('Tipo primitivo', type(n))
print('O objeto analisado é alfanumérico? ', n.isalnum())
print('O objeto analisado é alfabético? ', n.isalpha())
print('O objeto analisado é numérico? ', n.isnumeric())
print('O objeto analisado é um decimal? ', n.isdecimal())
print('O objeto analisado está só em letras minúsculas? ', n.islower())
print('O objeto analisado está só em letras maiúsculas? ', n.isupper())
print('O objeto analisado é um dígito? ', n.isdigit())
print('O objeto analisado é imprimível? ', n.isprintable())
print('O objeto analisado é um espaço? ', n.isspace())
print('O objeto analisado é um título? ', n.istitle())
print('O objeto analisado é identificado? ', n.isidentifier())
